### PR TITLE
Added Percona Server for MySQL

### PR DESCRIPTION
**Pull request by LenzGr**
Added Percona Server for MySQL to the list of applications.
Added link to Linux Distributions to the Getting Started Page.
Applied some minor typo fixes.

### CODE REVIEW

**Comment by damien-lemoal** [comment]
Manually applied with some tweaks to the commit messages.
In the last patch, I changed the text "Percona Server for MySQL" to be a link to: https://www.percona.com/software/mysql-database/percona-server.

All deployed now. Please check: https://zonedstorage.io/docs/applications/percona-server

Thanks !

**Comment by damien-lemoal** [comment]
One more thing I forgot to ask: what is the copyright and terms of use of the percona server logo image ? I want to make sure that it is OK to have it here on this site without breaking any license/terms-of-use. Did you get approval from Percona to allow its use here ?

**Comment by LenzGr** [comment]
> One more thing I forgot to ask: what is the copyright and terms of use of the percona server logo image ? I want to make sure that it is OK to have it here on this site without breaking any license/terms-of-use. Did you get approval from Percona to allow its use here ?

Yes, this in line with our [trademark policy](https://www.percona.com/trademark-policy) - thanks for double checking. To be extra sure, we could include a trademark notice somewhere (directly on the page?):
```
Percona Server and the Percona Server logo are trademarks of Percona, LLC
```

**Comment by damien-lemoal** [comment]
> Yes, this in line with our [trademark policy](https://www.percona.com/trademark-policy) - thanks for double checking. To be extra sure, we could include a trademark notice somewhere (directly on the page?):
> 
> ```
> Percona Server and the Percona Server logo are trademarks of Percona, LLC
> ```

Yes, it would be good to add this at the end of the page, and add a (tm) sign on the first iteration of Percona or any other trademarked word. And add the link to the trademark policy (which I checked, and while not being a lawyer, it seems to me like using the image is within the range of a "nominative fair use reference to a bona fide Percona product").

Can you send another patch ? Closing this issue.

Cheers.

**Pull request closed without merging**
